<?php

$european_countries = [
    'Albania'                   => 'Albania',
    'Andorra'                   => 'Andorra',
    'Armenia'                   => 'Armenia',
    'Austria'                   => 'Austria',
    'Azerbaijan'                => 'Azerbaijan',
    'Belarus'                   => 'Belarus',
    'Belgium'                   => 'Belgium',
    'Bosnia and Herzegovina'    => 'Bosnia and Herzegovina',
    'Bulgaria'                  => 'Bulgaria',
    'Croatia'                   => 'Croatia',
    'Cyprus'                    => 'Cyprus',
    'Czech Republic'            => 'Czech Republic',
    'Denmark'                   => 'Denmark',
    'Estonia'                   => 'Estonia',
    'Finland'                   => 'Finland',
    'France'                    => 'France',
    'Georgia'                   => 'Georgia',
    'Germany'                   => 'Germany',
    'Greece'                    => 'Greece',
    'Hungary'                   => 'Hungary',
    'Iceland'                   => 'Iceland',
    'Ireland'                   => 'Ireland',
    'Italy'                     => 'Italy',
    'Kazakhstan'                => 'Kazakhstan',
    'Latvia'                    => 'Latvia',
    'Liechtenstein'             => 'Liechtenstein',
    'Lithuania'                 => 'Lithuania',
    'Luxembourg'                => 'Luxembourg',
    'Malta'                     => 'Malta',
    'Moldova'                   => 'Moldova',
    'Monaco'                    => 'Monaco',
    'Montenegro'                => 'Montenegro',
    'Netherlands'               => 'Netherlands',
    'North Macedonia'           => 'North Macedonia',
    'Norway'                    => 'Norway',
    'Poland'                    => 'Poland',
    'Portugal'                  => 'Portugal',
    'Romania'                   => 'Romania',
    'Russia'                    => 'Russia',
    'San Marino'                => 'San Marino',
    'Serbia'                    => 'Serbia',
    'Slovakia'                  => 'Slovakia',
    'Slovenia'                  => 'Slovenia',
    'Spain'                     => 'Spain',
    'Sweden'                    => 'Sweden',
    'Switzerland'               => 'Switzerland',
    'Turkey'                    => 'Turkey',
    'Ukraine'                   => 'Ukraine',
    'United Kingdom'            => 'United Kingdom',
    'Vatican City'              => 'Vatican City'
];

return $european_countries;
